"""The generated tile.v1 classes plus the protobuf runtime, wherever it is.

    sys.path.insert(0, ".../icd/py"); import tilev1 as pb
    pb.Node(...), pb.to_json(msg), pb.from_json(text, pb.ListSegmentsRequest)

`google.protobuf` comes from the system when installed; otherwise from icd/vendor, the pure-Python
runtime deploy.sh ships to the board (the image has no pip). tile_pb2.py is generated by `make -C icd`
from tile.proto with the PC's protoc and committed, because the board has no protoc.
"""
import os
import sys

try:
    import google.protobuf  # noqa: F401
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "vendor"))
    import google.protobuf  # noqa: F401

from google.protobuf import json_format  # noqa: E402
from google.protobuf.message import Message  # noqa: E402,F401

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tile_pb2 import *  # noqa: E402,F401,F403
from tile_pb2 import DESCRIPTOR  # noqa: E402

API_VERSION = "1.1"   # 1.1: RecordingStatus.live_clients (proxy substream) and Fault.K_LOCAL (beacon)
CAPABILITIES = ("core", "recording", "trigger.local", "trigger.external", "trigger.log", "segments", "sessions",
                "locks", "live", "metrics", "config.live_sensor")
# rpc name -> (request class, reply class), from the service descriptor
METHODS = {m.name: (m.input_type._concrete_class, m.output_type._concrete_class)
           for m in DESCRIPTOR.services_by_name["Tile"].methods}


def to_json(msg):
    return json_format.MessageToJson(msg, indent=None)


def from_json(text, cls):
    """Raises json_format.ParseError on a malformed body; unknown fields are ignored (readers ignore them)."""
    return json_format.Parse(text or "{}", cls(), ignore_unknown_fields=True)
