"""Write sei/tests/vectors.txt from a Python sei module (the twin, or the frozen reference in backup/).

    python3 sei/tests/make_vectors.py [module_dir]     default: sei/python

Lines: `C codec` switches the codec of every line after it (h265 first, then h264),
`R epoch k ts sensor flags nal_hex` (build_sei of that record), `S stream_hex` followed by one
`A nal_hex nal_hex …` per access unit of that stream, and `I au_index R… nal_hex insert_hex`.
"""
import importlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "..", "python"))
sei = importlib.import_module("sei")

RECORDS = [(1, 0, 0, 0, 0), (7, 41200, 123456789012, 65535, 6), (0, 0, 0, 0, 0), (65535, 2**32 - 1, 2**64 - 1, 65535, 65535),
           (2, 3, 0x0000000100000002, 0, 0x0100), (1, 0x00000100, 0x0000030000000300, 3, 0)]
SC4, SC3 = b"\x00\x00\x00\x01", b"\x00\x00\x01"

# H.265: VPS/SPS/PPS, an IDR and two P slices of one picture. H.264: the same shape one NAL header shorter,
# SPS standing in for the VPS. Both exercise the first-slice bit, a 3-byte start code and a trailing zero.
H265 = dict(first_ps=bytes([32 << 1, 1, 0xAA]), sps=bytes([33 << 1, 1, 0xBB]), pps=bytes([34 << 1, 1, 0xCC]),
            idr=bytes([19 << 1, 1, 0x80, 0x11]), p_first=bytes([1 << 1, 1, 0x80, 0x22]), p_more=bytes([1 << 1, 1, 0x00, 0x33]))
H264 = dict(first_ps=bytes([0x67, 0xAA]), sps=bytes([0x67, 0xBB]), pps=bytes([0x68, 0xCC]),
            idr=bytes([0x65, 0x88, 0x11]), p_first=bytes([0x41, 0x88, 0x22]), p_more=bytes([0x41, 0x08, 0x33]))


def streams(n, codec):
    b = lambda r: sei.build_sei(sei.pack_record(*r), codec)   # noqa: E731
    return [
        SC4 + n["first_ps"] + SC4 + n["sps"] + SC3 + n["pps"] + SC4 + n["idr"] + SC4 + n["p_first"] + SC3 + n["p_more"] + SC4 + n["p_first"],
        SC4 + n["first_ps"] + SC4 + n["sps"] + SC4 + n["pps"] + b((1, 5, 9, 5, 0)) + SC4 + n["idr"]
        + b((1, 6, 10, 6, 0)) + SC4 + n["p_first"] + SC3 + n["p_more"]
        + SC4 + n["first_ps"] + SC4 + n["sps"] + SC4 + n["pps"] + b((1, 7, 11, 7, 8)) + SC4 + n["idr"],
        SC3 + n["p_first"] + SC3 + n["p_first"] + b"\x00\x00\x00\x00\x01" + n["p_first"],
    ]


with open(os.path.join(HERE, "vectors.txt"), "w") as f:
    f.write("# generated by make_vectors.py; both sei implementations must reproduce every line\n")
    for codec, n in (("h265", H265), ("h264", H264)):
        f.write("C %s\n" % codec)
        for r in RECORDS:
            f.write("R %d %d %d %d %d %s\n" % (*r, sei.build_sei(sei.pack_record(*r), codec).hex()))
        for s in streams(n, codec):
            f.write("S %s\n" % s.hex())
            for au in sei.access_units([s[i:i + 5] for i in range(0, len(s), 5)], codec):
                f.write("A %s\n" % " ".join(x.hex() for x in au))
        # insert: the Python twin re-serializes NALs with 4-byte start codes, the C++ keeps the AU's bytes;
        # they agree on a stream whose start codes are all 4 bytes long, which is what the parsers emit
        s = SC4 + n["first_ps"] + SC4 + n["sps"] + SC4 + n["pps"] + SC4 + n["idr"] + SC4 + n["p_first"]
        au = next(sei.access_units([s], codec))
        r = (1, 5, 9, 5, 0)
        f.write("I 0 %d %d %d %d %d %s %s\n" % (*r, s.hex(), sei.insert_sei(au, sei.build_sei(sei.pack_record(*r), codec), codec).hex()))
print("vectors.txt written from", sei.__file__)
